import prisma from '@/lib/prisma';
import { recordAuditLog } from '@/lib/audit/logger';
import { AuditAction } from '@prisma/client';

export interface AIDocumentExtractionResult {
  documentType: string;
  patientFound: { name?: string; age?: number; gender?: string };
  diagnosesMentioned: string[];
  proceduresMentioned: string[];
  medications: string[];
  labValues: Record<string, string>;
  imagingFindings: string[];
  previousSurgeries: string[];
  doctorRecommendations: string[];
  missingInformation: string[];
  confidence: number;
  extractedAt: string;
  disclaimer: string;
}

export interface AICaseSummaryResult {
  patientContext: string;
  existingDiagnosis: string;
  previousTreatment: string;
  currentRecommendation: string;
  relevantReports: string[];
  medications: string[];
  potentialTreatment: string;
  missingInformation: string[];
  questionsForClinician: string[];
  generatedAt: string;
  disclaimer: string;
}

export class MedicalAIService {
  private static readonly DISCLAIMER = 
    'INFORMATIONAL EXTRACTION ONLY: This summary is generated by an automated extraction system for administrative and workflow coordination. It does NOT constitute a medical diagnosis, prescription, or clinical decision.';

  /**
   * FEATURE 1: Document Extraction Pipeline
   */
  static async extractDocument(params: {
    documentId: string;
    documentStorageKey: string;
    category: string;
    userId: string;
  }): Promise<AIDocumentExtractionResult> {
    const { documentId, category, userId } = params;

    // Simulated high-precision clinical extraction
    const extraction: AIDocumentExtractionResult = {
      documentType: category || 'DIAGNOSTIC_REPORT',
      patientFound: {
        name: 'Ali Al-Balushi',
        age: 54,
        gender: 'Male',
      },
      diagnosesMentioned: [
        'Triple Vessel Coronary Artery Disease (CAD)',
        'Chronic Stable Angina (CCS Class III)',
        'Type 2 Diabetes Mellitus',
      ],
      proceduresMentioned: [
        'Coronary Angiography (Radial Access)',
        'Surgical Revascularization (CABG) Recommended',
      ],
      medications: [
        'Tab. Aspirin 75mg once daily',
        'Tab. Atorvastatin 40mg at bedtime',
        'Tab. Metformin 500mg twice daily',
      ],
      labValues: {
        'LVEF (Left Ventricular Ejection Fraction)': '52% (Preserved Systolic Function)',
        'Serum Creatinine': '1.1 mg/dL (Normal Renal Function)',
        'HbA1c': '7.2% (Moderate Glycemic Control)',
      },
      imagingFindings: [
        'Left Anterior Descending (LAD): 90% discrete stenosis in mid segment',
        'Right Coronary Artery (RCA): 85% tubular stenosis in proximal segment',
        'Left Circumflex (LCx): 70% lesion in distal branch',
      ],
      previousSurgeries: ['None reported'],
      doctorRecommendations: [
        'Patient advised for elective Coronary Artery Bypass Grafting (CABG) with arterial grafting to LAD.',
      ],
      missingInformation: [
        '2D Echocardiogram Detailed Wall Motion Report',
        'Recent Carotid Doppler Study',
      ],
      confidence: 0.96,
      extractedAt: new Date().toISOString(),
      disclaimer: this.DISCLAIMER,
    };

    // Save AI extraction in database and audit
    await recordAuditLog({
      entityName: 'MedicalDocument',
      entityId: documentId,
      userId,
      action: AuditAction.UPDATE,
      reason: 'AI clinical document extraction pipeline executed',
      newValues: { extractionConfidence: extraction.confidence },
    });

    return extraction;
  }

  /**
   * FEATURE 2: Case Summary Generation for Authorized Clinicians
   */
  static async generateCaseSummary(caseId: string, userId: string): Promise<AICaseSummaryResult> {
    const summary: AICaseSummaryResult = {
      patientContext: '54-year-old male from Muscat, Oman with 4-month history of exertional chest pain and shortness of breath.',
      existingDiagnosis: 'Severe Triple Vessel Coronary Artery Disease (I25.10) with preserved ejection fraction.',
      previousTreatment: 'Optimized medical therapy (Antiplatelets, Statins, Beta-blockers) with persistent angina on exertion.',
      currentRecommendation: 'Off-Pump Coronary Artery Bypass Grafting (OPCABG) utilizing Left Internal Mammary Artery (LIMA) to LAD and saphenous vein grafts.',
      relevantReports: [
        'Coronary Angiography (Muscat, Aug 2026) - 90% LAD, 85% RCA, 70% LCx',
        'Renal Function & Electrolytes - Creatinine 1.1 mg/dL',
      ],
      medications: ['Aspirin 75mg', 'Atorvastatin 40mg', 'Metformin 500mg'],
      potentialTreatment: 'Inpatient admission (7 days: 2 ICU + 5 Deluxe Room) + 7 days recovery.',
      missingInformation: [
        'Recent 2D Echo Report for regional wall motion abnormalities',
        'Pre-operative viral markers (HBsAg, HCV, HIV) as required by Indian hospitals',
      ],
      questionsForClinician: [
        'Is endoscopic vein harvesting (EVH) preferred for graft harvesting?',
        'Does the patient require pre-admission endocrinology consult for peri-operative glycemic protocol?',
      ],
      generatedAt: new Date().toISOString(),
      disclaimer: this.DISCLAIMER,
    };

    await recordAuditLog({
      entityName: 'MedicalCase',
      entityId: caseId,
      userId,
      action: AuditAction.READ,
      reason: 'Generated AI Case Summary for Clinical Review team',
    });

    return summary;
  }

  /**
   * FEATURE 4: Missing Document Detection
   */
  static async detectMissingDocuments(params: {
    categoryRequired: string[];
    uploadedCategories: string[];
  }): Promise<{ isComplete: boolean; missingList: string[] }> {
    const missing = params.categoryRequired.filter(
      (cat) => !params.uploadedCategories.includes(cat)
    );
    return {
      isComplete: missing.length === 0,
      missingList: missing,
    };
  }

  /**
   * FEATURE 6: Patient Operational Concierge
   */
  static handleConciergeQuery(query: string, caseData: any): { response: string; isMedicalEscalation: boolean } {
    const lower = query.toLowerCase();

    // Guardrail: Detect clinical / diagnostic questions and safely route to human clinical team
    if (lower.includes('pain') || lower.includes('bleed') || lower.includes('dose') || lower.includes('prescribe') || lower.includes('symptom') || lower.includes('fever')) {
      return {
        response: 'For any clinical symptoms, pain, or medication questions, our platform immediately routes your inquiry to your treating medical team and Care Coordinator. Please contact your local doctor immediately if experiencing acute emergency symptoms.',
        isMedicalEscalation: true,
      };
    }

    if (lower.includes('visa') || lower.includes('vil')) {
      return {
        response: `Your Indian Medical Visa Invitation Letter (VIL) from ${caseData.hospital || 'the hospital'} has been generated. You can download it directly from your Visa tab and submit it on indianvisaonline.gov.in.`,
        isMedicalEscalation: false,
      };
    }

    if (lower.includes('hotel') || lower.includes('stay') || lower.includes('accommodation')) {
      return {
        response: 'Your accommodation is planned at Courtyard by Marriott Gurugram (1.8 km from Medanta). Companion stay is included with wheelchair accessibility and flexible check-in.',
        isMedicalEscalation: false,
      };
    }

    if (lower.includes('driver') || lower.includes('pickup') || lower.includes('airport')) {
      return {
        response: 'Your driver Rajesh Kumar (+91 98765 43210) will receive you at Delhi Airport (DEL Terminal 3) with a name placard and dedicated sanitized AC car.',
        isMedicalEscalation: false,
      };
    }

    return {
      response: `Your current journey stage is "${caseData.currentStage || 'PROPOSAL_READY'}". Your assigned Care Coordinator Sarah Fernandes is available to assist you via WhatsApp and Portal Chat.`,
      isMedicalEscalation: false,
    };
  }
}
